name: ieee-fx
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip=23.2.1
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - cpuonly
  - numpy=1.24.4
  - pandas=2.1.1
  - scikit-learn=1.3.1
  - matplotlib=3.8.0
  - pip:
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - black==24.10.0
      - ruff==0.6.8
      - mypy==1.13.0
      - pyarrow==17.0.0
      - psutil==7.1.2
      - pytz==2024.2
      - pytest==7.4.2
