{
  "version": "v_07",
  "file_path": "./csv/EURUSD_Candlestick_1_Hour_BID_01.01.2010-18.02.2025.csv",
  "base_dir": "./IEEE_TNNLS_Runs_V7_Standardized",
  "data": {
    "time_steps": 3,
    "train_ratio": 0.96,
    "val_ratio": 0.02,
    "test_ratio": 0.02
  },
  "training": {
    "epochs": 60,
    "batch_size": 5000
  },
  "callbacks": {
    "early_stopping_patience": 60,
    "reduce_lr_patience": 1,
    "reduce_lr_factor": 0.1,
    "min_lr": 5e-7
  },
  "model": {
    "block_configs": [
      {"filters": 8, "kernel_size": 3, "pool_size": null}
    ],
    "num_heads_res_block": 3,
    "key_dim_res_block": 4,
    "leaky_relu_alpha_conv1_res_block": 0.04,
    "leaky_relu_alpha_conv2_res_block": 0.03,
    "leaky_relu_alpha_after_add_res_block": 0.03,
    "conv_l2_reg_res_block": 0.0,
    "num_bilstm_layers": 1,
    "lstm_units": 200,
    "recurrent_dropout_lstm": 0.0,
    "lstm_l2_reg": 0.0,
    "use_batchnorm_after_lstm": false,
    "use_batchnorm_after_post_lstm_mha": true,
    "moe_num_experts": 12,
    "moe_units": 64,
    "moe_leaky_relu_alpha": 0.01,
    "use_batchnorm_after_moe": true,
    "output_activation": "linear",
    "output_l2_reg": 0.0,
    "optimizer_lr": 0.01,
    "optimizer_weight_decay": null,
    "optimizer_clipnorm": null,
    "optimizer_clipvalue": null
  },
  "metadata": {
    "legacy_version": "v_07",
    "default_output_dir_name": "IEEE_TNNLS_Runs_V7_Standardized"
  },
  "dependencies": {
    "data_loader": "v_07.DataLoader.DataLoader",
    "model_builder": "v_07.ModelBuilder.ModelBuilder",
    "trainer": "v_07.Trainer.Trainer",
    "evaluator": "v_07.Evaluator.Evaluator",
    "history_manager": "v_07.HistoryManager.HistoryManager"
  },
  "runtime": {
    "seed": 42,
    "mixed_precision": {
      "enabled": true,
      "policy": "mixed_float16"
    }
  },
  "cli": {
    "flags": {
      "data_file": {"path": "file_path", "type": "path"},
      "output_dir": {"path": "base_dir", "type": "path"},
      "time_steps": {"path": "data.time_steps", "type": "int"},
      "epochs": {"path": "training.epochs", "type": "int"},
      "batch_size": {"path": "training.batch_size", "type": "int"},
      "num_heads_res_block": {"path": "model.num_heads_res_block", "type": "int"},
      "key_dim_res_block": {"path": "model.key_dim_res_block", "type": "int"},
      "leaky_alpha_conv1_res_block": {"path": "model.leaky_relu_alpha_conv1_res_block", "type": "float"},
      "leaky_alpha_conv2_res_block": {"path": "model.leaky_relu_alpha_conv2_res_block", "type": "float"},
      "leaky_alpha_after_add_res_block": {"path": "model.leaky_relu_alpha_after_add_res_block", "type": "float"},
      "conv_l2_reg_res_block": {"path": "model.conv_l2_reg_res_block", "type": "float"},
      "num_bilstm_layers": {"path": "model.num_bilstm_layers", "type": "int"},
      "lstm_units": {"path": "model.lstm_units", "type": "int"},
      "lstm_l2_reg": {"path": "model.lstm_l2_reg", "type": "float"},
      "moe_num_experts": {"path": "model.moe_num_experts", "type": "int"},
      "moe_units": {"path": "model.moe_units", "type": "int"},
      "moe_leaky_relu_alpha": {"path": "model.moe_leaky_relu_alpha", "type": "float"},
      "optimizer_lr": {"path": "model.optimizer_lr", "type": "float"},
      "output_l2_reg": {"path": "model.output_l2_reg", "type": "float"}
    },
    "toggles": {
      "disable_mixed_precision": {"path": "runtime.mixed_precision.enabled", "value": false}
    }
  }
}
