{
  "version": "v_01",
  "file_path": "./csv/EURUSD_Candlestick_1_Hour_BID_01.01.2010-18.02.2025.csv",
  "base_dir": "./IEEE_TNNLS_Runs_V1_Standard",
  "data": {
    "time_steps": 3,
    "train_ratio": 0.94,
    "val_ratio": 0.03,
    "test_ratio": 0.03
  },
  "training": {
    "epochs": 60,
    "batch_size": 5000
  },
  "callbacks": {
    "early_stopping_patience": 60,
    "reduce_lr_patience": 1,
    "reduce_lr_factor": 0.1,
    "min_lr": 5e-07
  },
  "model": {
    "block_configs": [],
    "filters_conv1": 8,
    "kernel_size_conv1": 3,
    "leaky_relu_alpha_conv1": 0.04,
    "use_pooling_conv1": false,
    "pool_size_conv1": null,
    "conv1_l2_reg": 0.0,
    "filters_conv2": 8,
    "kernel_size_conv2": 3,
    "leaky_relu_alpha_conv2": 0.03,
    "use_pooling_conv2": false,
    "pool_size_conv2": null,
    "conv2_l2_reg": 0.0,
    "num_bilstm_layers": 1,
    "lstm_units": 200,
    "recurrent_dropout_lstm": 0.0,
    "lstm_l2_reg": 0.0,
    "use_batchnorm_after_lstm": false,
    "use_batchnorm_after_attention": true,
    "use_dropout_before_output": false,
    "dropout_rate_before_output": 0.0,
    "output_activation": "linear",
    "output_l2_reg": 0.0,
    "optimizer_lr": 0.01,
    "optimizer_weight_decay": null,
    "optimizer_clipnorm": null,
    "optimizer_clipvalue": null
  },
  "metadata": {
    "legacy_version": "v_01",
    "default_output_dir_name": "IEEE_TNNLS_Runs_V1_Standard"
  },
  "dependencies": {
    "data_loader": "v_01.dependencies.create_data_loader",
    "model_builder": "v_01.dependencies.create_model_builder",
    "trainer": "v_01.dependencies.create_trainer",
    "evaluator": "v_01.dependencies.create_evaluator",
    "history_manager": "v_01.dependencies.create_history_manager",
    "hooks": "v_01.dependencies.build_hooks"
  },
  "runtime": {
    "seed": 42,
    "mixed_precision": {
      "enabled": false,
      "policy": "mixed_float16"
    }
  },
  "cli": {
    "flags": {
      "data_file": {
        "path": "file_path",
        "type": "path"
      },
      "output_dir": {
        "path": "base_dir",
        "type": "path"
      },
      "time_steps": {
        "path": "data.time_steps",
        "type": "int"
      },
      "epochs": {
        "path": "training.epochs",
        "type": "int"
      },
      "batch_size": {
        "path": "training.batch_size",
        "type": "int"
      },
      "filters_conv1": {
        "path": "model.filters_conv1",
        "type": "int"
      },
      "kernel_size_conv1": {
        "path": "model.kernel_size_conv1",
        "type": "int"
      },
      "leaky_alpha_conv1": {
        "path": "model.leaky_relu_alpha_conv1",
        "type": "float"
      },
      "lstm_units": {
        "path": "model.lstm_units",
        "type": "int"
      },
      "recurrent_dropout_lstm": {
        "path": "model.recurrent_dropout_lstm",
        "type": "float"
      },
      "optimizer_lr": {
        "path": "model.optimizer_lr",
        "type": "float"
      },
      "l2_reg_output": {
        "path": "model.output_l2_reg",
        "type": "float"
      }
    },
    "toggles": {
      "enable_mixed_precision": {
        "path": "runtime.mixed_precision.enabled",
        "value": true
      }
    }
  }
}